config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  resources :movies
  resources :directors
  resources :actors
  resources :reviews

  resources :users

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  has_many :roles

end

app/models/director.rb
class Director < ActiveRecord::Base

  has_many :movies
  
end

app/models/imdb.rb
class IMDB

  def self.all
    @data ||= [
      {
        id: '1',
        year: 1981,
        title: 'Raiders of the Lost Ark',
        image_url: 'raiders.jpg',
        plot: 'Archaeologist and adventurer Indiana Jones is hired by the US government to find the Ark of the Covenant before the Nazis.'
      },
      {
        id: '3',
        year: 1995,
        title: 'Apollo 13',
        image_url: 'apollo13.jpg',
        plot: 'NASA must devise a strategy to return Apollo 13 to Earth safely after the spacecraft undergoes massive internal damage putting the lives of the three astronauts on board in jeopardy.'
      },
      {
        id: '4',
        year: 2000,
        title: 'Cast Away',
        image_url: 'castaway.jpg',
        plot: 'A FedEx executive must transform himself physically and emotionally to survive a crash landing on a deserted island.'
      },
      {
        id: '5',
        title: "Jurassic Park",
        image_url: "jurassic.jpg",
        plot: "In Steven Spielberg's massive blockbuster, paleontologists Alan Grant (Sam Neill) and Ellie Sattler (Laura Dern) and mathematician Ian Malcolm (Jeff Goldblum) are among a select group chosen to tour an island theme park populated by dinosaurs created from prehistoric DNA. While the park's mastermind, billionaire John Hammond (Richard Attenborough), assures everyone that the facility is safe, they find out otherwise when various ferocious predators break free and go on the hunt.",
        year: 1993
      },
      {
        id: '8',
        title: "A Beautiful Mind",
        image_url: "mind.jpg",
        plot: "A human drama inspired by events in the life of John Forbes Nash Jr., and in part based on the biography \"A Beautiful Mind\" by Sylvia Nasar. From the heights of notoriety to the depths of depravity, John Forbes Nash Jr. experienced it all. A mathematical genius, he made an astonishing discovery early in his career and stood on the brink of international acclaim. But the handsome and arrogant Nash soon found himself on a painful and harrowing journey of self-discovery.",
        year: 2001
      },
      {
        id: '9',
        title: "Lincoln",
        image_url: "lincoln.jpg",
        plot: "With the nation embroiled in still another year with the high death count of Civil War, President Abraham Lincoln (Daniel Day-Lewis) brings the full measure of his passion, humanity and political skill to what would become his defining legacy: to end the war and permanently abolish slavery through the 13th Amendment. Having great courage, acumen and moral fortitude, Lincoln pushes forward to compel the nation, and those in government who oppose him, to aim toward a greater good for all mankind.",
        year: 2012
      }
    ]
  end

  def self.find_by(criteria)
    all.detect do |m|
      criteria.all? { |k,v| m[k.to_sym].to_s.downcase == v.to_s.downcase ||
                            m[k.to_sym].to_s.downcase =~ /#{v.to_s.downcase}/ }
    end
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  belongs_to :director  #, foreign_key: :director_id, class_name: "Director"

  has_many :roles  #, foreign_key: :movie_id, class_name: 'Role'
  has_many :actors, :through => :roles

end

app/models/role.rb
class Role < ActiveRecord::Base

  belongs_to :actor
  belongs_to :movie

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find_by(id: params[:id])
    if @actor == nil
      redirect_to "/actors"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController

  def index
    @directors = Director.all
  end

  def show
    @director = Director.find_by(id: params[:id])
  end

  def new

  end

  def create
    director = Director.new
    director.name = params[:name]
    director.photo_url = params[:photo_url]
    director.save
    redirect_to "http://localhost:3000/movies"
  end

  def edit
    @director = Director.find_by(id: params[:id])
  end

  def update
    director = Director.find_by(id: params[:id])
    director.name = params[:name]
    director.photo_url = params[:photo_url]
    director.save
    redirect_to "http://localhost:3000/movies"
  end

  def destroy
    director = Director.find_by(id: params[:id])
    director.delete
    redirect_to "http://localhost:3000/movies"
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
    if params[:keyword].present?
      @movies = @movies.where("title LIKE '%#{params[:keyword]}%'")
    end

    respond_to do |format|
      format.html do
        render 'index'
      end
      format.json do
        render json: @movies
      end
      format.xml do
        render xml: @movies
      end
    end


    # render 'index'  # Render index.html.erb
  end

  def create
    movie = Movie.new
    movie.title = params[:title]
    movie.plot = params[:plot]
    movie.image_url = params[:image_url]
    movie.director_id = params[:director_id]
    movie.year = params[:year]
    movie.save
    redirect_to movies_url
  end

  def show
    @movie = Movie.find_by(id: params[:id])
    if @movie == nil
      redirect_to movies_url
    end
    cookies["movie_id"] = @movie.id
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find_by(id: params[:id])
  end

  def update
    movie = Movie.find_by(id: params[:id])
    movie.title = params[:title]
    movie.plot = params[:plot]
    movie.image_url = params[:image_url]
    movie.year = params[:year]
    movie.save
    redirect_to movies_url(@movie)
  end

  def destroy
    movie = Movie.find_by(id: params[:id])
    if movie
      movie.delete
    end
    redirect_to movies_url
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    Rails.logger.debug "We should probably save the review to the database..."
    redirect_to movies_url
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user
      if user.password == params[:password]
        cookies["user_id"] = user.id
        redirect_to movies_url
        return
      end
    end
    redirect_to movies_url
  end

  def destroy
    cookies.delete("user_id")
    reset_session
    redirect_to movies_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new
    user.name = params[:user][:name]
    user.email = params[:user][:email]
    user.password = params[:user][:password]
    user.save
    redirect_to movies_url
  end

  def destroy
    User.delete(params[:id])
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/index.html.erb
<ul>
  <% @actors.each do |actor| %>
    <li><%= link_to actor.name, "/actors/#{actor.id}" %></li>
  <% end %>
</ul>

app/views/actors/show.html.erb
<h1><%= @actor.name %></h1>

<h3>Filmography</h3>

<ul>
  <% @actor.roles.each do |role| %>
    <li><%= link_to role.movie.title, "/movies/#{role.movie.id}" %></li>
  <% end %>
</ul>

app/views/directors/index.html.erb
<ul>
<% @directors.each do |director| %>
  <li><%= link_to director.name, "/directors/#{director.id}" %></li>
<% end %>
</ul>

app/views/directors/show.html.erb
<h1><%= @director.name %></h1>

<div class="details">
  <%= image_tag @director.photo_url, class: 'pull-right', width: '200px'  %>

  <h3>Filmography</h3>

  <ul>
    <% movies = Movie.where(director_id: @director.id) %>
    <% movies.each do |movie| %>
      <li><%= link_to movie.title, "/movies/#{movie.id}" %></li>
    <% end %>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuyFlix</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <ul>
      <li><%= link_to "Movies", movies_path %></li>
      <li><%= link_to "Directors", directors_path %></li>
      <li><%= link_to "Actors", actors_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <%= form_tag movies_url, :method => :get do %>
        <%= text_field_tag :keyword, '', placeholder: 'Search by title...' %>
      <% end %>
    </ul>
    <ul class="nav-right">
      <% if cookies["user_id"].present? %>
        <li><%= link_to "Sign Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Sign In", login_path %></li>
      <% end %>
    </ul>
  </nav>

  <div class="container">

    <%= yield %>

  </div>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |form| %>

  <p><%= form.label :title %>
  <br>
  <%= form.text_field :title, size: 80, autofocus: true %></p>

  <p><%= form.label :director_id, "Director" %>
  <br>
  <%= form.collection_select :director_id, Director.all.order('name'), :id, :name %></p>
  <p><%= form.label :year %>
  <br>
  <%= form.text_field :year %></p>

  <%= form.label :image_url,  "Link to poster URL" %>
  <br>
  <%= form.text_field :image_url, size: 80 %>

  <p><%= form.label :plot %>
  <br>
  <%= form.text_area :plot, rows: 4, cols: 80 %></p>

  <%= form.submit %>
<% end %>

app/views/movies/_movie.html.erb
<% poster_url = movie ? movie.image_url : 'add_new.png' %>
<% path = movie ? movie_path(movie.id) : new_movie_path %>

<div class="movie-box">
  <%= link_to image_tag(poster_url), path %>
  <% if movie %>
    <h3><%= link_to movie.title, movie_path(movie.id) %></h3>
  <% end %>
</div>

app/views/movies/edit.html.erb
<h2>Edit Movie #<%= @movie.id %></h2>

<%= render 'form' %>

app/views/movies/index.html.erb
<%= User.find_by(id: cookies["user_id"]).name if cookies["user_id"].present? %>

<aside>
  <h3>Recommended For You</h3>
  <% if cookies["movie_id"].present? %>
    <%= render Movie.find_by(id: cookies["movie_id"]) %>
  <% else %>
    <%= render Movie.sample %>
  <% end %>
</aside>

<div class="movie-selections">
  <%= render 'movie', movie: nil %>
  <%= render @movies %>
</div>

app/views/movies/new.html.erb
<h2>Add a New Movie</h2>

<%= render 'form' %>

app/views/movies/show.html.erb
<h1>
  <%= @movie.title %>
  <small>
    <%= link_to "Edit This Movie", edit_movie_path(@movie.id) %>
    <%= link_to "Delete This Movie", movie_path(@movie.id), :method => :delete %>
  </small>
</h1>

<div class="details">

  <p><%= image_tag @movie.image_url, class: 'pull-right' %></p>

  <p><strong>Directed By: </strong>
    <%= link_to @movie.director.name, "/directors/#{@movie.director.id}" %>
  </p>

  <p><strong>Released:</strong> <%= @movie.year %></p>
  <p><strong>Plot:</strong> <%= @movie.plot %></p>


  <p><strong>Actors: </strong></p>

  <ul>
    <% @movie.actors.each do |actor| %>
      <li><%= link_to actor.name, "/actors/#{actor.id}" %></li>
    <% end %>
  </ul>

  <h3>Add a Review</h3>

  <%= form_tag "/reviews", :method => :post do %>
    <%= label_tag :body, "What did you think?" %>
    <!-- <input type="hidden" name="movie_id" value="<%= @movie.id %>"> -->
    <%= hidden_field_tag :movie_id, @movie.id %>
    
    <br>
    <%= text_area_tag :body, '', rows: 4, cols: 50 %>
    <br>
    <%= submit_tag "Add Review" %>
  <% end %>

  <h3>Reviews</h3>

  <p><strong>Jeff said:</strong>
    A pretty cool movie if you like boring nonsense.  The cinematography looked
    like a child made it, and the acting was amatuerish.  Other than, it was
    great!
  </p>

  <p><strong>Borja said:</strong>
    A great example of computer science and society at large!
  </p>

  <p><strong>Neil said:</strong>
    Gravitons, photons, and neutrons, oh my!  Putting aside the obvious problems
    with the scientific basis of the fiction in this movie, it wasn't too bad.
  </p>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <p><%= f.label :name %><%= f.text_field :name, size: 40, autofocus: true, required: true %></p>
  <p><%= f.label :email %><%= f.text_field :email, size: 40, required: true %></p>
  <p><%= f.label :password %><%= f.text_field :password, size: 40, required: true %></p>
  <p><%= f.submit "Sign Me Up!" %></p>

<% end %>